### ISSUE TITLE
One question in pre-processing does not show up

### ISSUE THREAD

**Issue by asoskic** [Remi-Gau/artemis_checklist#11]
Question “What action did you take regarding artifacts in step 2?” only occurs for step 2, but not step 1…? It’s in the spreadsheet in row 19, but not in the app.

**Comment by Remi-Gau** [comment]
This was because some cells in the spreadsheet were empty: https://docs.google.com/spreadsheets/d/1dlUt8_bHsM5mERFJkVLTVWanSlms6Ba8Wos38Dhmhfo/edit#gid=1276614777&range=J34:K34

I filled them in and now the item appears as expected.
