### ISSUE TITLE
many visibility issues

### ISSUE THREAD

**Issue by Remi-Gau** [Remi-Gau/artemis_checklist#2]
Mentioned on the UI repo

https://github.com/ReproNim/reproschema-ui/issues/234

**Comment by asoskic** [comment]
Update: visibility given a condition seems to work in some cases, and not in others.

E.g: in the beginning of hardware section, if I pick "single electrodes" I will not get questions about caps, but in the beginning of acquisition section, I will be asked about the impedance threshold regardless of whether I opt for impedances or and alternative data quality indicator

**Comment by Remi-Gau** [comment]
Will close this now as this is too generic: better from now on to open specific issues for each visibility problem that arises
