### ISSUE TITLE
Question "What determined the number of trials each subject was presented with?" does not show up

### ISSUE THREAD

**Issue by asoskic** [Remi-Gau/artemis_checklist#20]
This question "What determined the number of trials each subject was presented with?" in the Design and Sample section does not show up.

It may be that I have resolved this, but I am leaving the issue so that we can check just in case: `item_order` value was erroneously the same (i.e. 6) for this and previous question. I have fixed this now - let's see if the issue dissapears with the next update of the app. :)

**Comment by Remi-Gau** [comment]
This apparently is fixed now
