### ISSUE TITLE
The section "Study_ID" does not show up in the web-app

### ISSUE THREAD

**Issue by asoskic** [Remi-Gau/artemis_checklist#21]
This is the new, and now first section, and sheet of the cobidas_artemis web-app.

**Comment by Remi-Gau** [comment]
ah yeah I saw it in the spreadsheet but was not sure when it had 'appeared' will work on adding it

**Comment by Remi-Gau** [comment]
added to the conversion code but not yet rendered in the app

**Comment by Remi-Gau** [comment]
see here: https://github.com/Remi-Gau/eCobidas/commit/d128b32066aa39fdd77a510fd8efe3cce82d0014
