### ISSUE TITLE
Options don't show up for some radio button questions and one cannot progress

### ISSUE THREAD

**Issue by asoskic** [Remi-Gau/artemis_checklist#24]
Where did I notice this:
1) Item order 3 in pre-processing: "What kind of high-pass filter did you use?"
2) Item order 2 in measuremen: "The amplitude is measured from"

Options don't show up for these questions, and if you press "Skip" nothing happens (except that I see that something is briefly tries to load on my Firefox's "refresh" button. As a result, I cannot even get to further questions in this section.

I am not sure whether this has to do with anything, but I believe both of these are new preset variables :)

**Comment by Remi-Gau** [comment]
OK 
this was because the "preset" list of responses had not been updated online.

this should now be fixed
