### ISSUE TITLE
No preamble showing in the Channel section

### ISSUE THREAD

**Issue by KatarinaKetrinStekic** [Remi-Gau/artemis_checklist#33]
There is a preamble in the cobidas_artemis table, but it's not showing in the app.

**Comment by KatarinaKetrinStekic** [comment]
Same issue with the Visualization section.

**Comment by asoskic** [comment]
I found a possible solution for Visualization, just have to test whether it worked - the Preamble was placed not next to the first question, but the second - possibly not copied to its new place when a new question was added.

**Comment by Remi-Gau** [comment]
Both should be fixed now: if there is more than one cell filled in the preamble column of a given section, none will be displayed.
