### ISSUE TITLE
Last 2 questions in the Visualization section not showing

### ISSUE THREAD

**Issue by KatarinaKetrinStekic** [Remi-Gau/artemis_checklist#36]
The 2 questions after _"Rationale for selection of channel locations used for waveform presentation in the figure"_ are not appearing, the progress bar hits 100% after this question. I believe the issue is in the item_order column because these last 2 questions are numbered as 1 and 2, instead of 15 and 16.

**Comment by Remi-Gau** [comment]
Actually this is because even though they are in the same sheet, they actually constitute a different section in the App.
